<?php

/**
 * @file
 * Install, update and uninstall functions for the scrape_to_field module.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_install().
 */
function scrape_to_field_install() {
  $field_definition = BaseFieldDefinition::create('string_long')
    ->setName('field_scraper_config')
    ->setLabel(new TranslatableMarkup('Scrape to field Configuration'))
    ->setDescription(new TranslatableMarkup('Internal field to store scrape to field configuration data.'))
    ->setDefaultValue('')
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayConfigurable('view', FALSE)
    ->setDisplayOptions('form', [
      'region' => 'hidden',
    ])
    ->setDisplayOptions('view', [
      'region' => 'hidden',
    ]);

  $entity_definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $entity_definition_update_manager->installFieldStorageDefinition(
    'field_scraper_config',
    'node',
    'scrape_to_field',
    $field_definition
  );
}

/**
 * Implements hook_uninstall().
 */
function scrape_to_field_uninstall() {
  // Clean up configuration.
  \Drupal::configFactory()->getEditable('scrape_to_field.settings')->delete();
  \Drupal::state()->delete('scrape_to_field.last_cron_run');

  $connection = \Drupal::database();
  $connection->delete('key_value')
    ->condition('collection', 'state')
    ->condition('name', 'scrape_to_field.%', 'LIKE')
    ->execute();
}
